StoreApp/Controllers/Administration/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Data;

namespace StoreApp.Controllers.Administration
{
    public class UsersController : Controller
    {

        private readonly UserManager<StoreUser> _userManager;

        public UsersController(UserManager<StoreUser> userManager)
        {
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var users = _userManager.Users.ToArray();
            return View(users);
        }
    }
}

StoreApp/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BusinessLogic.Managers;
using BusinessLogic.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Data;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class BasketController : Controller
    {
        private BasketManager _manager;

        private IMapper _mapper;

        private UserManager<StoreUser> _userManager;

        public BasketController(BasketManager manager, IMapper mapper, UserManager<StoreUser> userManager)
        {
            _manager = manager ?? throw new ArgumentNullException(nameof(BasketManager));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(IMapper));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(UserManager<StoreUser>));

        }
        public IActionResult Index()
        {
            var product = _mapper.Map<IEnumerable<ProductModel>, IEnumerable<ProductViewModel>>(_manager.GetProductsFromBasket(_userManager.GetUserId(User)));
            return View(product);
        }

        public IActionResult ClearAll()
        {
            var userId = _userManager.GetUserId(User);

            _manager.Clear(userId);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int productId)
        {
            var userId = _userManager.GetUserId(User);
            _manager.Delete(userId, productId);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult SetProductCount(int productId)
        {
            if(productId > 0)
            {
                var userId = _userManager.GetUserId(User);
                var count = Convert.ToInt32(Request.Form[productId + "_count"]);
                if (count > 0)
                {
                    _manager.SetCount(userId, productId, count);
                }
            }

            return RedirectToAction("Index");
        }


    }
}

StoreApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BusinessLogic.Managers;
using BusinessLogic.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Data;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private UserManager<StoreUser> _userManager;
        private ProductManager _manager { get; set; }
        private IMapper _mapper { get; set; }

        public ProductController(
            ProductManager manager, 
            IMapper mapper,
            UserManager<StoreUser> userManager)
        {
            _manager = manager ?? throw new ArgumentNullException(nameof(ProductManager));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(IMapper));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(UserManager<StoreUser>));
        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index(int id)
        {

            var productsData = id == 0 ? _manager.GetAllProducts() : _manager.GetProducts(id);
            var products = _mapper.Map<IEnumerable<ProductModel>, IEnumerable<ProductViewModel>>(productsData);
            return View(products);
        }




        [HttpGet]
        [Authorize]
        public IActionResult Add(int id)
        {
            if(id != 0)
            {
                var userId = _userManager.GetUserId(User);
                _manager.AddProductToBasket(userId, id);
            }
            return RedirectToAction("Index");

        }
    }
}

StoreApp/ViewComponents/CategoryListViewComponent.cs
using AutoMapper;
using BusinessLogic.Managers;
using BusinessLogic.Models;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreApp.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private readonly CategoryManager _manager;

        private readonly IMapper _mapper;
        public CategoryListViewComponent(CategoryManager manager, IMapper mapper)
        {
            _manager = manager ?? throw new ArgumentNullException(nameof(CategoryManager));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(IMapper));
        }
        public IViewComponentResult Invoke()
        {
            var categories = GetCategories();
            return View(categories);
        }

        public IEnumerable<CategoryViewModel> GetCategories()
        {
            var categories = _manager.GetCategories();
            return _mapper.Map<IEnumerable<CategoryModel>, IEnumerable<CategoryViewModel>>(categories);
        }
    }
}

StoreApp/Views/Shared/ProductListPartial.cshtml
@model IEnumerable<ProductViewModel>

@foreach (var product in Model)
{
    <tr>

        

        <td>
            @product.Name
        </td>

        <td>
            @product.Price
        </td>

        <td>
            @product.CategoryName
        </td>

        @if ((bool)ViewData["IsBasket"])
        {
            <td> Delete from basket </td>
        }
        else
        {
            <td> <a asp-controller="Product" asp-action="Add" asp-route-id="@product.Id" >Add to basket</a></td>
        }



    </tr>

}

StoreApp/Views/Shared/_BasketPartialView.cshtml
@model IEnumerable<ProductViewModel>

@{ 
    ViewData["Count"] = 0;
}
@foreach (var product in Model)
{
    <tr>

        <td>
            @product.Name
        </td>

        <td>
            @product.Price
        </td>

        <td>
            @{ 
                var inputId = product.Id + "_count";
                ViewData["Count"] = @product.Count;
            }

            <form method="post"
                  asp-controller="Basket"
                  asp-action="SetProductCount"
                  asp-route-productId="@product.Id">

                <input style="width:50px"
                       type="number"
                       name="@inputId"
                       asp-for="@product.Count"
                        />
                <button class="btn" type="submit">
                    <i style="font-size:24px" class="fa">&#xf021;</i>
                </button>
            </form>

        </td>


        <td> <a asp-controller="Basket" asp-action="Delete" asp-route-productId="@product.Id">Delete</a></td>


    </tr>

}

StoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StoreApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StoreApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="_LoginPartial" />
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (!User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">Basket</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @await Component.InvokeAsync("CategoryList")
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - StoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

StoreApp/Views/Shared/_ProductListPartial.cshtml
@model IEnumerable<ProductViewModel>

@foreach (var product in Model)
{
    <tr>

        <td>
            @product.Name
        </td>

        <td>
            @product.Price
        </td>

        <td>
            @product.CategoryName
        </td>

        <td> <a asp-controller="Product" asp-action="Add" asp-route-id="@product.Id">Add to basket</a></td>

    </tr>

}